

// TOOL:     vlog2tf
// DATE:     Wed Apr 16 12:56:09 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   RemoteControllerSchematic
// DESIGN:   RemoteControllerSchematic
// FILENAME: RemoteControllerSchematic_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module RemoteControllerSchematic_tf();

// Inputs
    reg A;
    reg B;
    reg C;


// Outputs
    wire Ld;
    wire Le;
    wire Rd;
    wire Re;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    RemoteControllerSchematic UUT (
        .A(A), 
        .B(B), 
        .C(C), 
        .Ld(Ld), 
        .Le(Le), 
        .Rd(Rd), 
        .Re(Re)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 0;
            B = 0;
            C = 0;
    end

endmodule // RemoteControllerSchematic_tf